const assert = require("node:assert/strict");
const t = require("./logic.js");

const records = t.parseRecords('SKU;Nombre;Precio\r\nA;"con; separador";20\r\n\r\nB;"multilínea\r\ncon texto";21\r\n');
assert.deepEqual(records.map(r => r.line), [1, 2, 3, 4]);
assert.deepEqual(records[1].cells, ["A", "con; separador", "20"]);
assert.deepEqual(records[3].cells, ["B", "multilínea\ncon texto", "21"]);
assert.deepEqual(t.parse("\uFEFFA,B,C\r\n1,2,3\r\n"), [["A","B","C"],["1","2","3"]]);
assert.deepEqual(t.parse('A\tB\tC\n1\t2\t3'), [["A","B","C"],["1","2","3"]]);
assert.deepEqual(t.parse('A,B,C\n"a""b",x,10'), [["A","B","C"],['a"b',"x","10"]]);
assert.throws(() => t.parse('a;b\n"not closed;2'), /sin cerrar/);
assert.throws(() => t.parse('a;b\n"x"garbage;2'), /después de cerrar comillas/);
assert.throws(() => t.parse('a;b\n1;2;3'), /línea 2.*3 columnas/);
assert.equal(t.parsePrice("19,90"), 19.9);
assert.equal(t.parsePrice("19.90"), 19.9);
assert.equal(t.parsePrice("0"), 0);
assert.equal(t.parsePrice("999999999.99"), 999999999.99);
assert.equal(t.parsePrice("19.999"), null);
assert.equal(t.parsePrice("1.234,56"), null);
assert.equal(t.parsePrice("1,234"), null);
assert.equal(t.parsePrice("-25"), null);
assert.equal(t.parsePrice("1e9"), null);
assert.equal(t.parsePrice("12 34"), null);
assert.equal(t.parsePrice("1000000000"), null);

const sample="Codigo;Producto;Costo\nSKU-102;Teclado USB;42.50\nSKU-205;Mouse óptico;19,90\n;Adaptador;24.00\nSKU-205;Mouse extra;21.00";
const validated=t.validateRecords(t.parseRecords(sample).slice(1),[0,1,2]);
assert.equal(validated.length,4);
assert.deepEqual(validated.map(r=>r.line),[2,3,4,5]);
assert.equal(validated.filter(r=>r.errors.length===0).length,1);
assert.match(validated[1].errors.join(),/precios diferentes: 19.90 \/ 21.00/);
assert.match(validated[3].errors.join(),/nombres diferentes/);
assert.equal(validated[2].errors[0],"SKU vacío");
assert.equal(validated[0].sku,"SKU-102");
assert.equal(validated[1].price,19.9);

const same=t.validateRecords(t.parseRecords("sku,name,price\nA,N,2.00\na,N,2.00").slice(1),[0,1,2]);
assert.equal(same.filter(r=>r.errors.length>0).length,2);
assert.ok(same.every(r=>r.errors.some(e=>e.includes("datos repetidos"))));
const withBlanks=t.validateRecords(t.parseRecords("a;b;c\n\nSKU-1;Uno;1.00\n\nSKU-2;Dos;2.00").slice(1),[0,1,2]);
assert.deepEqual(withBlanks.map(r=>r.line),[3,5]);
assert.throws(()=>t.validateRecords(t.parseRecords(sample).slice(1),[0,0,2]),/diferentes/);
assert.match(t.serialize([["A","B"],['=HYPERLINK("x")',"content"]]), /^"A","B"\r\n"'=HYPERLINK\(""x""\)","content"\r\n$/);
assert.ok(t.serialize([["  =2+3","\n@SUM(1)"]]).includes("'  =2+3"));
assert.ok(t.serialize([["  =2+3","\n@SUM(1)"]]).includes("'\n@SUM(1)"));
assert.equal(t.parse(t.serialize([["Col1","Col2"],["Hola, mundo","multi\nlinea"]]))[1][0],"Hola, mundo");
console.log("PASS: 36 verificaciones lógicas (CSV, duplicados, precios, líneas, mapeo y seguridad de exportación).");
